### ISSUE TITLE
Getting this error and its flooding the alert. Tried what it asked but no success.

### ISSUE THREAD

**Issue by Igorcmb** [thatlonelybugbear/midi-srd#10]
![Captura de tela 2023-11-26 172541](https://github.com/thatlonelybugbear/midi-srd/assets/42787711/b55f09f1-cf8a-4850-893d-c3ee8d1210ff)

**Comment by thatlonelybugbear** [comment]
Have you tried with only MidiQOL/DAE/MidiSRD/socketlib/libwrapper modules active to see if that happens again?

To me, this seems like an issue with settings of another module.

**Comment by thatlonelybugbear** [comment]
This is an issue with CPR (Chris premades) module and Chris will update it to not throw that warning
