### ISSUE TITLE
forge compatibility issue

### ISSUE THREAD

**Issue by Alactaio** [thatlonelybugbear/midi-srd#17]
![Midi-Srd](https://github.com/user-attachments/assets/b03881c1-433c-47b7-b948-43dcfcb003d8)

**Comment by thatlonelybugbear** [comment]
Hey there, it's not an incompatibility with Forge or something, but rather me setting the maximum dnd5e compatible version as 2.4.1, to make sure no issues arise from Warpgate being a dependency.

I am working (slowly the truth is), on updating MidiSRD for Foundry v12 and latest dnd5e system version

I'll close this issue for now, until an update is out :)

See also #16
