### ISSUE TITLE
[Bug] Enhance Ability only has 5 of the 6 options that should be available 

### ISSUE THREAD

**Issue by Ghostdesu** [thatlonelybugbear/midi-srd#2]
![image](https://user-images.githubusercontent.com/31375910/204944417-caa1cd8a-25cc-47e8-9c8a-866fb07cfd4f.png)

Tested using most recent version of core, dnd5e and midi-srd and all the required modules.

**Comment by thatlonelybugbear** [comment]
This had slipped through the cracks. Fixed with <https://github.com/thatlonelybugbear/midi-srd/commit/0a8cee307268fc97cdc02e07a416d49c30093465> v10.0.9 of MidiSRD.

I would suggest giving a try to DFreds CE that is well integrated with MidiQOL and has all these spells premade!
