### ISSUE TITLE
Mismatch name file midiSRD-styles.css

### ISSUE THREAD

**Issue by gus-uktena** [thatlonelybugbear/midi-srd#3]
Having this error: it's looking for midiSRD-styles.css (plural) but, in the folder, the file is named midiSRD-style.css

![image](https://user-images.githubusercontent.com/83596301/225533657-3ad42363-9b88-4368-a036-99e82453dc6d.png)

**Comment by Vipe29** [comment]
Same here. Is there a fix for this?

**Comment by thatlonelybugbear** [comment]
I will push an update for v10 soon enough. 

Some IRL issues came up and had to push it a bit back

**Comment by thatlonelybugbear** [comment]
Release for v10. More updates from next week.
<https://github.com/thatlonelybugbear/midi-srd/releases/tag/10.10.1>
