### ISSUE TITLE
update animate dead to take into account Undead Thralls? 

### ISSUE THREAD

**Issue by ctbritt** [thatlonelybugbear/midi-srd#6]
Could this be updated to check for Undead Thralls, and if present, update the hp and damage of the zombie and skeleton, please? 
```
let thrallHp = 0 
let thrallDamage = 0
let extraThrall = 0
const undeadThralls = tactor.items.find(item => item.name === "Undead Thralls")
if (undeadThralls) {
	thrallHp = actorData.classes.wizard.levels;
	thrallDamage = prof;
        extralThall =+ 1

}
```

Then just add `thrallHp` and `thrallDamag` to the respective keys.

**Comment by thatlonelybugbear** [comment]
This is for the Necromancer Wizard ability correct?

This is not SRD available material unfortunately, so I won't be including it as is.

I could make the `await MidiMacros.animateDead(args)` call return the spawned ids and then you could further mutate them to update HPs and damage accordingly.

Or I could offer some extra customization by passing hp and damage parameters.
I will give it some thought for the next release.

**Comment by thatlonelybugbear** [comment]
The solution I think I will go with is this.
```js
await MidiMacros.animateDead(args,config)
 ```
 and the config can be something like
 ```js
const config = { texture:{zombie:"image path",skeleton:"image path"}, hp: "wizard.level"  , extra:1}
```
with:
- `texture`: which would change the default Zombie or skeleton image to the ones provided,
- `hp`: the extra hp which the spawned creatures will get, either a number or a string like shown to indicate use the level of the caster,
- `extra`: any number for changing the default number of creatures to be spawned.
